---
- name: Install openstack
  hosts: openstack
  vars:
    MARIADB_ROOT_PASSWORD: "{{ lookup('ansible.builtin.env', 'MARIADB_ROOT_PASSWORD') }}"
    KEYSTONE_DB_PASSWORD: "{{ lookup('ansible.builtin.env', 'KEYSTONE_DB_PASSWORD') }}"
    ADMIN_PASSWORD: "{{ lookup('ansible.builtin.env', 'ADMIN_PASSWORD') }}"
    GLANCE_DB_PASSWORD: "{{ lookup('ansible.builtin.env', 'GLANCE_DB_PASSWORD') }}"
    GLANCE_USER_PASSWORD: "{{ lookup('ansible.builtin.env', 'GLANCE_USER_PASSWORD') }}"
    PLACEMENT_DB_PASSWORD: "{{ lookup('ansible.builtin.env', 'PLACEMENT_DB_PASSWORD') }}"
    PLACEMENT_USER_PASSWORD: "{{ lookup('ansible.builtin.env', 'PLACEMENT_USER_PASSWORD') }}"
    RABBITMQ_DEFAULT_USER: "{{ lookup('ansible.builtin.env', 'RABBITMQ_DEFAULT_USER') }}"
    RABBITMQ_DEFAULT_PASSWORD: "{{ lookup('ansible.builtin.env', 'RABBITMQ_DEFAULT_PASSWORD') }}"
    NOVA_DB_PASSWORD: "{{ lookup('ansible.builtin.env', 'NOVA_DB_PASSWORD') }}"
    NOVA_USER_PASSWORD: "{{ lookup('ansible.builtin.env', 'NOVA_USER_PASSWORD') }}"
    MY_IP: "{{ lookup('ansible.builtin.env', 'MY_IP') }}"
    NEUTRON_DB_PASSWORD: "{{ lookup('ansible.builtin.env', 'NEUTRON_DB_PASSWORD') }}"
    NEUTRON_USER_PASSWORD: "{{ lookup('ansible.builtin.env', 'NEUTRON_USER_PASSWORD') }}"
    METADATA_SECRET: "{{ lookup('ansible.builtin.env', 'METADATA_SECRET') }}"
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: "{{ lookup('ansible.builtin.env', 'ADMIN_PASSWORD') }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: http://localhost:5000/v3
    OS_IDENTITY_API_VERSION: 3
  roles:
    - role: system
    - role: db
    - role: virtualenv
    - role: git
    - role: keystone
    - role: glance
    - role: rabbitmq