---
- name: Install packages
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt-daemon-system
    - novnc

- name: Start libivrtd Service
  become: true
  become_user: root
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: true
